services:
  db:
    image: mysql:8.0
    container_name: cotisations_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: EspaceMembreDB
    volumes:
      - ./db/espacemembre.sql:/docker-entrypoint-initdb.d/espacemembre.sql
      - db_data:/var/lib/mysql
    networks:
      - cotisations_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-prootpass"]
      interval: 10s
      timeout: 5s
      retries: 5

  php:
    build:
      context: .           # Le contexte est maintenant la racine du projet
      dockerfile: ./php/Dockerfile  # Le chemin vers le fichier Dockerfile
    container_name: cotisations_php
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - cotisations_network

  nginx:
    build: ./nginx  # <--- On build maintenant notre propre image Nginx
    container_name: cotisations_nginx
    restart: always
    ports:
      - "8081:80" 
    depends_on:
      - php
    networks:
      - cotisations_network

networks:
  cotisations_network:
    driver: bridge

volumes:
  db_data: