services:
  db:
    image: mysql:8.0
    container_name: cotisations_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: EspaceMembreDB
    volumes:
      - ./db/espacemembre.sql:/docker-entrypoint-initdb.d/espacemembre.sql
      - db_data:/var/lib/mysql
    networks:
      - cotisations_network
    healthcheck:
      # On teste si on peut faire un SELECT sur la table Membre. 
      # Tant que l'importation du .sql n'est pas finie, cette commande échouera.
      test: ["CMD", "mysql", "-u", "root", "-prootpass", "-e", "SELECT 1 FROM Membre LIMIT 1;", "EspaceMembreDB"]
      interval: 5s   # On vérifie toutes les 5 secondes
      timeout: 5s
      retries: 10
      start_period: 60s   # On essaie 15 fois (soit 75 secondes max pour l'initialisation)

  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: cotisations_php
    restart: always
    depends_on:
      db:
        condition: service_healthy # PHP attend que le test SELECT 1 de la DB réussisse
    networks:
      - cotisations_network

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: cotisations_nginx
    restart: always
    ports:
      - "8081:80" 
    depends_on:
      - php
    networks:
      - cotisations_network

  mailhog:
    image: mailhog/mailhog
    container_name: cotisations_mailhog
    ports:
      - "1025:1025" 
      - "8025:8025" 
    networks:
      - cotisations_network
      
networks:
  cotisations_network:
    driver: bridge

volumes:
  db_data: