server {
    listen 80;
    root /var/www/html;
    index Accueil.php index.php;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        fastcgi_pass php:9000;# Nom du service dans docker-compose
        fastcgi_index index.php;
        include fastcgi_params;
        # CRUCIAL : Cette ligne dit à PHP où chercher le fichier
        fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
    }
}
